import 'package:mood_book/model/mood_model.dart';

List<MoodModel> moods = [
  MoodModel(mood: MoodVarient.angry, month: "4"),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.fear),
  MoodModel(mood: MoodVarient.angry, month: "4"),
  MoodModel(mood: MoodVarient.happy),
  MoodModel(mood: MoodVarient.sad, month: "4"),
  MoodModel(mood: MoodVarient.happy),
  MoodModel(mood: MoodVarient.fear),
  MoodModel(mood: MoodVarient.angry, month: "4"),
  MoodModel(mood: MoodVarient.sad, month: "4"),
  MoodModel(mood: MoodVarient.happy),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.angry, month: "4"),
  MoodModel(mood: MoodVarient.angry, month: "4"),
  MoodModel(mood: MoodVarient.angry),
  MoodModel(mood: MoodVarient.surprise),
  MoodModel(mood: MoodVarient.angry, month: "4"),
  MoodModel(mood: MoodVarient.happy),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.sad),
  MoodModel(mood: MoodVarient.sad),
];
